// try{
// console.log("try block start here")
// //reference error
// console.log(x);
// }
// catch(err){
// //error ke saath aap kya karna chahte hai
// console.log("I am inside catch block");
// console.log("your error is here",err);
// }
// finally{
//     console.log("this will run everytime");
// }

/* let's create custom error*/

// try{
// console.log(x);
// }

// catch(err){
//     throw new Error("chal pehle declare kar")//khud ka error throw 
// }

// let errorCode=100;
// if(errorCode==100){
//     throw new Error("Invalid Json");
// }